#define DIO_DIO_PIN_0         INPUT_HIGH_IMP
#define DIO_DIO_PIN_1         INPUT_PULL_UP
#define DIO_DIO_PIN_2         OUTPUT_LOW
#define DIO_DIO_PIN_3         INPUT_HIGH_IMP
#define DIO_DIO_PIN_4         OUTPUT_HIGH
#define DIO_DIO_PIN_5         INPUT_PULL_UP
#define DIO_DIO_PIN_6         OUTPUT_HIGH
#define DIO_DIO_PIN_7         INPUT_HIGH_IMP
#define DIO_DIO_PIN_8         INPUT_HIGH_IMP
#define DIO_DIO_PIN_9         INPUT_PULL_UP
#define DIO_DIO_PIN_10         INPUT_PULL_UP
#define DIO_DIO_PIN_11         INPUT_PULL_UP
#define DIO_DIO_PIN_12         OUTPUT_LOW
#define DIO_DIO_PIN_13         OUTPUT_HIGH
#define DIO_DIO_PIN_14         OUTPUT_HIGH
#define DIO_DIO_PIN_15         OUTPUT_LOW
#define DIO_DIO_PIN_16         INPUT_HIGH_IMP
#define DIO_DIO_PIN_17         OUTPUT_HIGH
#define DIO_DIO_PIN_18         OUTPUT_LOW
#define DIO_DIO_PIN_19         INPUT_PULL_UP
#define DIO_DIO_PIN_20         OUTPUT_LOW
